spring:
  application:
    name:database

  spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/test_101
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  database:
    flush:
      batch-size: 2000

  insert:
    validateFields: true
