spring:
  application:
    name: database

  datasource:
    url: jdbc:postgresql://localhost:5433/test_101
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    postgresql:
      transactional: false
    validate-on-migrate: true
    out-of-order: true
    repair-on-migrate: true

  database:
    flush:
      batch-size: 2000

  insert:
    validateFields: true
